### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by m0rkeulv** [barisyild/sfs2x-api-haxe#1]
Just want to drop by and say i got a fork that i  use and that is pure Haxe code. i have fixed a few bugs and moved away from `haxe-crypto` and over to `crypto` (https://github.com/HaxeFoundation/crypto)
If you plan to do the same switch then my branch might come in handy  :)

https://github.com/m0rkeulv/smartfox-haxe-client

**Comment by barisyild** [comment]
Your fork looks really nice, I can add websocket support to your project if you wish.

**Advantages of WebSocket**

WebSocket allows firewall can help you connect on computers that don't allow socket.
It allows you to use your server on platforms like CloudFlare.
