### ISSUE TITLE
Socket error on Android 11

### ISSUE THREAD

**Issue by flashultra** [barisyild/sfs2x-api-haxe#2]
It's not possible to create connection when use Android 11 
I've got the following error:

**BitSwarmClient.hx:569: ## SocketError:[IOErrorEvent type="ioError" bubbles=true cancelable=false text="Connection failed" errorID=0]**

It works on Android 9 without any change in the code.

**Comment by DigiEggz** [comment]
Could this problem be related to Android 11's tightened security on certificates? Does your SmartFox server zone use encryption and HTTPS?

**Comment by flashultra** [comment]
Not sure where was the problem ( it possible to be in Android 11 ), but everything works now.
Thank you.
